# Generated by Django 4.2.11 on 2024-04-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnelmgmt', '0003_alter_department_doctors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='appointments',
        ),
        migrations.CreateModel(
            name='PatientAppointmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnelmgmt.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnelmgmt.patient')),
            ],
            options={
                'unique_together': {('patient', 'appointment')},
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='appointments',
            field=models.ManyToManyField(null=True, related_name='assigned_patients', through='personnelmgmt.PatientAppointmentAssignment', to='personnelmgmt.appointment'),
        ),
    ]
