# Generated by Django 4.2.11 on 2024-05-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnelmgmt', '0005_remove_patient_appointments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='appointments',
        ),
    ]
